language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - CI=false npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  github_token: FIREBASE_TOKEN
  local_dir: build
  on:
    branch: master
